# tasks file for ubuntu-1804-mariadb-server
---
- name: install | dependencies
  apt:
    name: "{{ item }}"
  with_items: "{{ ubuntu_1804_mariadb_server_dependencies }}"

- name: install | dependencies | check service
  service:
    name: mysql
    state: started
